# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f7a8080c709fb948570879bd523c02c714c7292ddfe94ae5d2a2a59998633a688171101f214a99688d2e4a594a9be21ad415e10446dd80706936637bd8a3869

test:
  secret_key_base: 56e7c5b7229c894d0325e74b270d98e1e1d07efe032c813f4ee3bad6ad6ca227f62742c1a5ad4958a510909a646b507abfaf5f6799423fd817c0df7f6f405260

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
